### ISSUE TITLE
Regressions introduced by pull requests

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#27]
@kylewm:

````
.....................F.F........
======================================================================
FAIL: test_parser.test_embedded_parsing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom/.virtualenvs/mf2py/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tom/code/mf2py/test/test_parser.py", line 198, in test_embedded_parsing
    '\n<p>Blah blah blah blah blah.</p>\n<p>Blah.</p>\n<p>Blah blah blah.</p>\n')
AssertionError: u'\n   <p>Blah blah blah blah blah.</p>\n   <p>Blah.</p>\n   <p>Blah blah blah.</p>\n  ' != '\n<p>Blah blah blah blah blah.</p>\n<p>Blah.</p>\n<p>Blah blah blah.</p>\n'

======================================================================
FAIL: test_parser.test_hoisting_nested_hcard
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom/.virtualenvs/mf2py/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tom/code/mf2py/test/test_parser.py", line 242, in test_hoisting_nested_hcard
    assert_equal([u'KP\nKP1'], result['items'][0]['properties']['name'])
AssertionError: Lists differ: [u'KP\nKP1'] != [u'KP\n    KP1']

First differing element 0:
KP
KP1
KP
    KP1

- [u'KP\nKP1']
+ [u'KP\n    KP1']
?        ++++


----------------------------------------------------------------------
Ran 32 tests in 0.654s

FAILED (failures=2)
````

**Comment by kylewm** [comment]
The `KP\nKP1` issue seems to have been introduced in March 2014 (!!) 32556ddeb713446a76ff98b3d3e144e8c063ba2f and I think the `blah blah` test goes back even farther. I'm guessing it depends on which backing html parser BS4 is using.

We should probably figure out what the output SHOULD be... It's not clear to me

**Comment by kylewm** [comment]
Turns out it was a difference between html5lib (the default for mf2py) and lxml (what I had installed in my venv for some reason). Sent a pull request that puts the whitespace back how it was before. Sorry!
