### ISSUE TITLE
infinite recursion crash

### ISSUE THREAD

**Issue by snarfed** [tommorris/mf2py#78]
on v1.0.5, parsing https://julieannenoying.com/category/photography/ with python 3.6, BeautifulSoup 4, and lxml crashes with the infinite recursion below.

seems specific to python 3 and/or lxml; html5lib with python 2.7 (maybe?) works fine on https://mf2.kylewm.com/?url=http%3A%2F%2Fjulieannenoying.com%2Fcategory%2Fphotography%2F&parser=html5lib .

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 39, in parse
    return Parser(doc, url, html_parser).to_dict()
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 112, in __init__
    self.parse()
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 359, in parse
    parse_el(self.__doc__, ctx, True)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 355, in parse_el
    parse_el(child, ctx)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 355, in parse_el
    parse_el(child, ctx)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 355, in parse_el
    parse_el(child, ctx)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 350, in parse_el
    result = handle_microformat(potential_microformats, el)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 136, in handle_microformat
    child_props, child_children = parse_props(child)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 283, in parse_props
    child_properties, child_microformats = parse_props(child)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 283, in parse_props
    child_properties, child_microformats = parse_props(child)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 278, in parse_props
    children.append(handle_microformat(root_class_names, el))
... [last four frames repeated many times]
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 212, in parse_props
    p_value = text_type(parse_property.text(el).strip())
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parse_property.py", line 40, in text
    value_els = get_vcp_children(el)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parse_property.py", line 33, in get_vcp_children
    return [c for c in get_children(el) if c.has_attr('class')
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parse_property.py", line 33, in <listcomp>
    return [c for c in get_children(el) if c.has_attr('class')
RecursionError: maximum recursion depth exceeded
```

**Comment by snarfed** [comment]
confirmed, it's lxml. parsing with html5lib on python 3.6 works ok.

it's a substantial size page, 542KB HTML and ~100KB parsed mf2 JSON, but i doubt that alone is the root cause here.

**Comment by snarfed** [comment]
found another one that happens with both lxml and html5lib: http://www.downes.ca/research_authors.htm . similarly big-ish, 708KB HTML. it crashes @kylewm's online util too, https://mf2.kylewm.com/?url=http://www.downes.ca/research_authors.htm (sorry kyle!)

here's the html5lib traceback:
```
Traceback (most recent call last):
  File "/Users/ryan/src/indie-map/bigquery/warc_to_bigquery.py", line 172, in <module>
    main(sys.argv[1:])
  File "/Users/ryan/src/indie-map/bigquery/warc_to_bigquery.py", line 51, in main
    row = maybe_convert(record, domain)
  File "/Users/ryan/src/indie-map/bigquery/warc_to_bigquery.py", line 145, in maybe_convert
    mf2 = mf2py.parse(url=url, doc=BeautifulSoup(body, 'html5lib'))
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 39, in parse
    return Parser(doc, url, html_parser).to_dict()
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 97, in __init__
    if el.name == 'base'), None)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 96, in <genexpr>
    poss_base = next((el for el in get_descendents(self.__doc__)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/dom_helpers.py", line 42, in get_descendents
    for desc in get_descendents(child):
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/dom_helpers.py", line 42, in get_descendents
    for desc in get_descendents(child):
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/dom_helpers.py", line 42, in get_descendents
    for desc in get_descendents(child):
  [Previous line repeated 986 more times]
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/dom_helpers.py", line 40, in get_descendents
    for child in get_children(node):
RecursionError: maximum recursion depth exceeded
```

**Comment by sknebel** [comment]
Can't reproduce the first one (presumably julie has changed her markup), the second one *has* hundreds/thousands of levels of nested markup (due to having not closed `<admin ....>` tags in front of every line), so it's not surprising the Recursion Limit is hit. You could manually increase it by using ` sys.setrecursionlimit()`.

The code could be changed to not use recursion here, but I'm not sure that's justified.

**Comment by tommorris** [comment]
I feel like @sknebel's answer here seems about right. If a non-trivial number of pages were coded such that the recursion limit were being hit, it'd be worth changing.

It might be worth documenting pages likely to trigger recursion-based parsers, possibly on the Microformats wiki. It certainly seems like it might be possible to write a parser that _isn't_ recursion-based (an event-based parser like SAX seems like a good starting point), but porting multiple language implementations over to it if only a small number of pages are affected might be a _lot_ of effort that could be better spent.

I'm going to leave this issue open for another week or so for comments. If anyone wants to fix this by fundamentally rewriting the code base, I'd certainly be open to that ("patches welcome" as the cliche goes), but I think the amount of engineering might not be worth it unless more cases of this can be identified.

**Comment by snarfed** [comment]
agreed! totally makes sense to leave this as is. I'm fine with that.

the one thing you might consider is formalizing the error handling a bit. either document that mf2py.parse may raise RecursionError on unusually big pages, or catch and re-raise as a different exception, or something similar.

up to you all though. thanks for looking!

**Comment by snarfed** [comment]
Hit this again just now on another HTML page in the wild, https://www.panas.org.il/post/הקונספציה-של-זנד

See https://www.panas.org.il/post/הקונספציה-של-זנד
